# Generated by Django 6.1.1 on 2026-09-25 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del genero, por ejemplo: Ciencia ficcion.', max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo de la persona.', max_length=120)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo original de la pelicula.', max_length=200)),
                ('year', models.PositiveIntegerField(help_text='Ano de estreno. 1888 es la primera proyeccion filmica.', validators=[django.core.validators.MinValueValidator(1888)])),
                ('summary', models.TextField(blank=True, help_text='Sinopsis breve.')),
                ('cover', models.ImageField(blank=True, help_text='Portada de la pelicula. Requiere Pillow.', null=True, upload_to='covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('genres', models.ManyToManyField(blank=True, help_text='Generos de la pelicula.', related_name='movies', to='movies.genre')),
                ('people', models.ManyToManyField(blank=True, help_text='Reparto y equipo tecnico.', related_name='movies', to='movies.person')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='Puntuacion de 1 a 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True, help_text='Comentario opcional de quien valora.')),
                ('author', models.CharField(blank=True, help_text='Nombre de quien emite la valoracion.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima modificacion')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie', verbose_name='pelicula')),
            ],
            options={
                'verbose_name': 'Valoracion',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['year'], name='movie_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('author', ''), _negated=True), fields=('movie', 'author'), name='unique_rating_per_author_and_movie'),
        ),
    ]
