# Generated by Django 6.1.1 on 2026-09-25 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Nombre del genero, por ejemplo: Ciencia ficcion.', max_length=80, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, help_text='Portada de la pelicula. Requiere Pillow.', null=True, upload_to='covers/', verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Generos de la pelicula.', related_name='movies', to='movies.genre', verbose_name='generos'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='people',
            field=models.ManyToManyField(blank=True, help_text='Reparto y equipo tecnico.', related_name='movies', to='movies.person', verbose_name='reparto'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True, help_text='Sinopsis breve.', verbose_name='sinopsis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Titulo original de la pelicula.', max_length=200, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(help_text='Ano de estreno. 1888 es la primera proyeccion filmica.', validators=[django.core.validators.MinValueValidator(1888)], verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Nombre completo de la persona.', max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='author',
            field=models.CharField(blank=True, help_text='Nombre de quien emite la valoracion.', max_length=120, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, help_text='Comentario opcional de quien valora.', verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(help_text='Puntuacion de 1 a 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='puntuacion'),
        ),
    ]
